### ISSUE TITLE
EPIC: 

### ISSUE THREAD

**Issue by quarkusbot** [maxandersen/githubaction-testinggrounds#35]
something else 

## Epic items
(this section is auto-generated - manual edits will get lost)
- [ ] [#30](https://github.com/maxandersen/githubaction-testinggrounds/issues/30) hibernate
- [ ] [#2](https://github.com/maxandersen/githubaction-testinggrounds/issues/2) Testing create issue from jbang
- [x] [#32](https://github.com/maxandersen/githubaction-testinggrounds/issues/32) jjj
