### ISSUE TITLE
EPIC: Testing Checklists

### ISSUE THREAD

**Issue by paulrobinson** [maxandersen/githubaction-testinggrounds#36]
Description

[cosmetic change]

Checklist goes here:

## Epic items
(this section is auto-generated - manual edits will get lost)
- [ ] [#4](https://github.com/maxandersen/githubaction-testinggrounds/issues/4) Testing create issue from jbang
- [ ] [#5](https://github.com/maxandersen/githubaction-testinggrounds/issues/5) Testing create issue from jbang
- [ ] [#6](https://github.com/maxandersen/githubaction-testinggrounds/issues/6) Testing create issue from jbang
- [x] [#37](https://github.com/maxandersen/githubaction-testinggrounds/issues/37) testing automation of checklists on Epics
