### ISSUE TITLE
EPIC: Test from emmanuel

### ISSUE THREAD

**Issue by emmanuelbernard** [maxandersen/githubaction-testinggrounds#38]
## Epic items
(this section is auto-generated - manual edits will get lost)
- [ ] [#4](https://github.com/maxandersen/githubaction-testinggrounds/issues/4) Testing create issue from jbang
- [ ] [#5](https://github.com/maxandersen/githubaction-testinggrounds/issues/5) Testing create issue from jbang
- [ ] [#36](https://github.com/maxandersen/githubaction-testinggrounds/issues/36) EPIC: Testing Checklists
